// This file has been generated by Py++.

// (C) Christopher Woods, GPL >= 3 License

#ifndef ComponentConstraint_hpp__pyplusplus_wrapper
#define ComponentConstraint_hpp__pyplusplus_wrapper

void register_ComponentConstraint_class();

#endif//ComponentConstraint_hpp__pyplusplus_wrapper
