// This file has been generated by Py++.

// (C) Christopher Woods, GPL >= 3 License

#ifndef IDAssigner_hpp__pyplusplus_wrapper
#define IDAssigner_hpp__pyplusplus_wrapper

void register_IDAssigner_class();

#endif//IDAssigner_hpp__pyplusplus_wrapper
