// This file has been generated by Py++.

// (C) Christopher Woods, GPL >= 3 License

#ifndef IDOrSet_MonitorID__hpp__pyplusplus_wrapper
#define IDOrSet_MonitorID__hpp__pyplusplus_wrapper

void register_IDOrSet_MonitorID__class();

#endif//IDOrSet_MonitorID__hpp__pyplusplus_wrapper
