// This file has been generated by Py++.

// (C) Christopher Woods, GPL >= 3 License

#ifndef MonitorComponent_hpp__pyplusplus_wrapper
#define MonitorComponent_hpp__pyplusplus_wrapper

void register_MonitorComponent_class();

#endif//MonitorComponent_hpp__pyplusplus_wrapper
