// This file has been generated by Py++.

// (C) Christopher Woods, GPL >= 3 License

#ifndef MonitorProperty_hpp__pyplusplus_wrapper
#define MonitorProperty_hpp__pyplusplus_wrapper

void register_MonitorProperty_class();

#endif//MonitorProperty_hpp__pyplusplus_wrapper
