// This file has been generated by Py++.

// (C) Christopher Woods, GPL >= 3 License

#ifndef NullConstraint_hpp__pyplusplus_wrapper
#define NullConstraint_hpp__pyplusplus_wrapper

void register_NullConstraint_class();

#endif//NullConstraint_hpp__pyplusplus_wrapper
