// This file has been generated by Py++.

// (C) Christopher Woods, GPL >= 3 License

#ifndef PolariseCharges_hpp__pyplusplus_wrapper
#define PolariseCharges_hpp__pyplusplus_wrapper

void register_PolariseCharges_class();

#endif//PolariseCharges_hpp__pyplusplus_wrapper
