// This file has been generated by Py++.

// (C) Christopher Woods, GPL >= 3 License

#ifndef WindowedComponent_hpp__pyplusplus_wrapper
#define WindowedComponent_hpp__pyplusplus_wrapper

void register_WindowedComponent_class();

#endif//WindowedComponent_hpp__pyplusplus_wrapper
