// This file has been generated by Py++.

// (C) Christopher Woods, GPL >= 3 License

#ifndef ChargeElementParameterNames3D_hpp__pyplusplus_wrapper
#define ChargeElementParameterNames3D_hpp__pyplusplus_wrapper

void register_ChargeElementParameterNames3D_class();

#endif//ChargeElementParameterNames3D_hpp__pyplusplus_wrapper
