// This file has been generated by Py++.

// (C) Christopher Woods, GPL >= 3 License

#ifndef GTO_hpp__pyplusplus_wrapper
#define GTO_hpp__pyplusplus_wrapper

void register_GTO_class();

#endif//GTO_hpp__pyplusplus_wrapper
