// This file has been generated by Py++.

// (C) Christopher Woods, GPL >= 3 License

#ifndef GTOPair_hpp__pyplusplus_wrapper
#define GTOPair_hpp__pyplusplus_wrapper

void register_GTOPair_class();

#endif//GTOPair_hpp__pyplusplus_wrapper
