// This file has been generated by Py++.

// (C) Christopher Woods, GPL >= 3 License

#ifndef Molpro_hpp__pyplusplus_wrapper
#define Molpro_hpp__pyplusplus_wrapper

void register_Molpro_class();

#endif//Molpro_hpp__pyplusplus_wrapper
