// This file has been generated by Py++.

// (C) Christopher Woods, GPL >= 3 License

#ifndef NullQMChargeCalculator_hpp__pyplusplus_wrapper
#define NullQMChargeCalculator_hpp__pyplusplus_wrapper

void register_NullQMChargeCalculator_class();

#endif//NullQMChargeCalculator_hpp__pyplusplus_wrapper
