// This file has been generated by Py++.

// (C) Christopher Woods, GPL >= 3 License

#ifndef OrbitalShell_hpp__pyplusplus_wrapper
#define OrbitalShell_hpp__pyplusplus_wrapper

void register_OrbitalShell_class();

#endif//OrbitalShell_hpp__pyplusplus_wrapper
