// This file has been generated by Py++.

// (C) Christopher Woods, GPL >= 3 License

#ifndef QMMMFF_hpp__pyplusplus_wrapper
#define QMMMFF_hpp__pyplusplus_wrapper

void register_QMMMFF_class();

#endif//QMMMFF_hpp__pyplusplus_wrapper
