// This file has been generated by Py++.

// (C) Christopher Woods, GPL >= 3 License

#ifndef S_GTO_hpp__pyplusplus_wrapper
#define S_GTO_hpp__pyplusplus_wrapper

void register_S_GTO_class();

#endif//S_GTO_hpp__pyplusplus_wrapper
