// This file has been generated by Py++.

// (C) Christopher Woods, GPL >= 3 License

#ifndef ShellPair_hpp__pyplusplus_wrapper
#define ShellPair_hpp__pyplusplus_wrapper

void register_ShellPair_class();

#endif//ShellPair_hpp__pyplusplus_wrapper
