// This file has been generated by Py++.

// (C) Christopher Woods, GPL >= 3 License

#ifndef SS_GTO_hpp__pyplusplus_wrapper
#define SS_GTO_hpp__pyplusplus_wrapper

void register_SS_GTO_class();

#endif//SS_GTO_hpp__pyplusplus_wrapper
