#!/bin/bash

while (( "$#" )); do
  case "$1" in
    -b|--branch)
      if [ -n "$2" ] && [ ${2:0:1} != "-" ]; then
        BRANCH=$2
        shift 2
      else
        echo "Error: Argument for $1 is missing" >&2
        exit 1
      fi
      ;;
    -l|--lib)
      if [ -n "$2" ] && [ ${2:0:1} != "-" ]; then
        LIB=$2
        shift 2
      else
        echo "Error: Argument for $1 is missing" >&2
        exit 1
      fi
      ;;

    -*|--*=) # unsupported flags
      echo "Error: Unsupported flag $1" >&2
      exit 1
      ;;
  esac
done

if [[ -z "${BRANCH+set}" ]]; then
    BRANCH="devel"
fi

cd $HOME

echo "Generating wrappers for branch $BRANCH"

if [[ -f "/opt/conda/includes.tar.bz2" ]]
then
    echo "Extracting headers for Sire dependencies"
    cd /opt/conda && \
       tar -jxvf includes.tar.bz2 && \
       rm includes.tar.bz2 && \
       cd $HOME
fi

if [[ -d "Sire" ]]
then
    echo "Removing old Sire directory..."
    rm -rf Sire
fi

echo "Checking out sire..."
git clone --branch $BRANCH https://github.com/openbiosim/sire

echo "Changing into the wrapper directory..."
cd sire/wrapper

echo "Running scanheaders..."
python AutoGenerate/scanheaders.py $HOME/sire/corelib/src/libs .

if [ -z "$LIB" ]
then
    echo "No library specified, generating all wrappers..."
    python create_all_wrappers.py
else
    echo "Generating wrappers for $LIB..."
    cd $LIB
    python ../AutoGenerate/create_wrappers.py
fi

echo "Complete"
