// This file has been generated by Py++.

// (C) Christopher Woods, GPL >= 3 License

#ifndef CPUID_hpp__pyplusplus_wrapper
#define CPUID_hpp__pyplusplus_wrapper

void register_CPUID_class();

#endif//CPUID_hpp__pyplusplus_wrapper
