// This file has been generated by Py++.

// (C) Christopher Woods, GPL >= 3 License

#ifndef IntegerArrayProperty_hpp__pyplusplus_wrapper
#define IntegerArrayProperty_hpp__pyplusplus_wrapper

void register_IntegerArrayProperty_class();

#endif//IntegerArrayProperty_hpp__pyplusplus_wrapper
