// This file has been generated by Py++.

// (C) Christopher Woods, GPL >= 3 License

#ifndef NoMangling_hpp__pyplusplus_wrapper
#define NoMangling_hpp__pyplusplus_wrapper

void register_NoMangling_class();

#endif//NoMangling_hpp__pyplusplus_wrapper
