// This file has been generated by Py++.

// (C) Christopher Woods, GPL >= 3 License

#ifndef PageCache_hpp__pyplusplus_wrapper
#define PageCache_hpp__pyplusplus_wrapper

void register_PageCache_class();

#endif//PageCache_hpp__pyplusplus_wrapper
