// This file has been generated by Py++.

// (C) Christopher Woods, GPL >= 3 License

#ifndef SimpleRange_hpp__pyplusplus_wrapper
#define SimpleRange_hpp__pyplusplus_wrapper

void register_SimpleRange_class();

#endif//SimpleRange_hpp__pyplusplus_wrapper
