// This file has been generated by Py++.

// (C) Christopher Woods, GPL >= 3 License

#ifndef TrimString_hpp__pyplusplus_wrapper
#define TrimString_hpp__pyplusplus_wrapper

void register_TrimString_class();

#endif//TrimString_hpp__pyplusplus_wrapper
