// This file has been generated by Py++.

// (C) Christopher Woods, GPL >= 3 License

#ifndef UpperCaseString_hpp__pyplusplus_wrapper
#define UpperCaseString_hpp__pyplusplus_wrapper

void register_UpperCaseString_class();

#endif//UpperCaseString_hpp__pyplusplus_wrapper
