// This file has been generated by Py++.

// (C) Christopher Woods, GPL >= 3 License


#include "boost/python.hpp"

#include "boost/python/suite/indexing/vector_indexing_suite.hpp"

#include "EMLECallback.pypp.hpp"

#include "EMLEEngine.pypp.hpp"

#include "LambdaLever.pypp.hpp"

#include "OpenMMMetaData.pypp.hpp"

#include "PerturbableOpenMMMolecule.pypp.hpp"

#include "QMForce.pypp.hpp"

#include "_SireOpenMM_free_functions.pypp.hpp"

#include "vector_less__OpenMM_scope_Vec3__greater_.pypp.hpp"

namespace bp = boost::python;

#include "SireOpenMM_registrars.h"

#include "./register_extras.h"

BOOST_PYTHON_MODULE(_SireOpenMM){
    register_SireOpenMM_objects();

    register_vector_less__OpenMM_scope_Vec3__greater__class();

    register_EMLECallback_class();

    register_QMForce_class();

    register_EMLEEngine_class();

    register_LambdaLever_class();

    register_OpenMMMetaData_class();

    register_PerturbableOpenMMMolecule_class();

    SireOpenMM::register_extras();

    register_free_functions();
}

