// This file has been generated by Py++.

// (C) Christopher Woods, GPL >= 3 License

#ifndef EMLEForce_hpp__pyplusplus_wrapper
#define EMLEForce_hpp__pyplusplus_wrapper

void register_EMLEForce_class();

#endif//EMLEForce_hpp__pyplusplus_wrapper
