// This file has been generated by Py++.

// (C) Christopher Woods, GPL >= 3 License

#ifndef EMLECallback_hpp__pyplusplus_wrapper
#define EMLECallback_hpp__pyplusplus_wrapper

void register_EMLECallback_class();

#endif//EMLECallback_hpp__pyplusplus_wrapper
