// This file has been generated by Py++.

// (C) Christopher Woods, GPL >= 3 License

#ifndef EMLEEngine_hpp__pyplusplus_wrapper
#define EMLEEngine_hpp__pyplusplus_wrapper

void register_EMLEEngine_class();

#endif//EMLEEngine_hpp__pyplusplus_wrapper
