// This file has been generated by Py++.

// (C) Christopher Woods, GPL >= 3 License

#ifndef QMEngine_hpp__pyplusplus_wrapper
#define QMEngine_hpp__pyplusplus_wrapper

void register_QMEngine_class();

#endif//QMEngine_hpp__pyplusplus_wrapper
