// This file has been generated by Py++.

// (C) Christopher Woods, GPL >= 3 License

#ifndef QMForce_hpp__pyplusplus_wrapper
#define QMForce_hpp__pyplusplus_wrapper

void register_QMForce_class();

#endif//QMForce_hpp__pyplusplus_wrapper
