//WARNING - AUTOGENERATED FILE - CONTENTS WILL BE OVERWRITTEN!
#include <Python.h>

#include "SireOpenMM_registrars.h"

#include "emle.h"
#include "lambdalever.h"
#include "openmmmolecule.h"

#include "Helpers/objectregistry.hpp"

void register_SireOpenMM_objects()
{

    ObjectRegistry::registerConverterFor< SireOpenMM::EMLECallback >();
    ObjectRegistry::registerConverterFor< SireOpenMM::EMLEEngine >();
    ObjectRegistry::registerConverterFor< SireOpenMM::EMLECallback >();
    ObjectRegistry::registerConverterFor< SireOpenMM::EMLEEngine >();
    ObjectRegistry::registerConverterFor< SireOpenMM::LambdaLever >();
    ObjectRegistry::registerConverterFor< SireOpenMM::LambdaLever >();
    ObjectRegistry::registerConverterFor< SireOpenMM::PerturbableOpenMMMolecule >();
    ObjectRegistry::registerConverterFor< SireOpenMM::PerturbableOpenMMMolecule >();

}

