// This file has been generated by Py++.

// (C) Christopher Woods, GPL >= 3 License

#include "boost/python.hpp"
#include "boost/python/suite/indexing/vector_indexing_suite.hpp"
#include "vector_less__OpenMM_scope_Vec3__greater_.pypp.hpp"

#include <OpenMM.h>

namespace bp = boost::python;

void register_vector_less__OpenMM_scope_Vec3__greater__class(){

    { //::std::vector< OpenMM::Vec3 >
        typedef bp::class_< std::vector< OpenMM::Vec3 > > vector_less__OpenMM_scope_Vec3__greater__exposer_t;
        vector_less__OpenMM_scope_Vec3__greater__exposer_t vector_less__OpenMM_scope_Vec3__greater__exposer = vector_less__OpenMM_scope_Vec3__greater__exposer_t( "vector_less__OpenMM_scope_Vec3__greater_", "" );
        bp::scope vector_less__OpenMM_scope_Vec3__greater__scope( vector_less__OpenMM_scope_Vec3__greater__exposer );
        vector_less__OpenMM_scope_Vec3__greater__exposer.def( bp::vector_indexing_suite< ::std::vector< OpenMM::Vec3 > >() );
    }

}
