// This file has been generated by Py++.

// (C) Christopher Woods, GPL >= 3 License

#ifndef ID_hpp__pyplusplus_wrapper
#define ID_hpp__pyplusplus_wrapper

void register_ID_class();

#endif//ID_hpp__pyplusplus_wrapper
