// This file has been generated by Py++.

// (C) Christopher Woods, GPL >= 3 License

#ifndef Index_hpp__pyplusplus_wrapper
#define Index_hpp__pyplusplus_wrapper

void register_Index_class();

#endif//Index_hpp__pyplusplus_wrapper
