// This file has been generated by Py++.

// (C) Christopher Woods, GPL >= 3 License

#ifndef CenterOfMass_hpp__pyplusplus_wrapper
#define CenterOfMass_hpp__pyplusplus_wrapper

void register_CenterOfMass_class();

#endif//CenterOfMass_hpp__pyplusplus_wrapper
