// This file has been generated by Py++.

// (C) Christopher Woods, GPL >= 3 License

#ifndef Center_hpp__pyplusplus_wrapper
#define Center_hpp__pyplusplus_wrapper

void register_Center_class();

#endif//Center_hpp__pyplusplus_wrapper
