// This file has been generated by Py++.

// (C) Christopher Woods, GPL >= 3 License

#ifndef FF_hpp__pyplusplus_wrapper
#define FF_hpp__pyplusplus_wrapper

void register_FF_class();

#endif//FF_hpp__pyplusplus_wrapper
