// This file has been generated by Py++.

// (C) Christopher Woods, GPL >= 3 License

#ifndef FFName_hpp__pyplusplus_wrapper
#define FFName_hpp__pyplusplus_wrapper

void register_FFName_class();

#endif//FFName_hpp__pyplusplus_wrapper
