// This file has been generated by Py++.

// (C) Christopher Woods, GPL >= 3 License

#ifndef MolEnergyTable_hpp__pyplusplus_wrapper
#define MolEnergyTable_hpp__pyplusplus_wrapper

void register_MolEnergyTable_class();

#endif//MolEnergyTable_hpp__pyplusplus_wrapper
