// This file has been generated by Py++.

// (C) Christopher Woods, GPL >= 3 License

#ifndef PotentialTable_hpp__pyplusplus_wrapper
#define PotentialTable_hpp__pyplusplus_wrapper

void register_PotentialTable_class();

#endif//PotentialTable_hpp__pyplusplus_wrapper
