// This file has been generated by Py++.

// (C) Christopher Woods, GPL >= 3 License

#ifndef GridIndex_hpp__pyplusplus_wrapper
#define GridIndex_hpp__pyplusplus_wrapper

void register_GridIndex_class();

#endif//GridIndex_hpp__pyplusplus_wrapper
