// This file has been generated by Py++.

// (C) Christopher Woods, GPL >= 3 License

#ifndef Patching_hpp__pyplusplus_wrapper
#define Patching_hpp__pyplusplus_wrapper

void register_Patching_class();

#endif//Patching_hpp__pyplusplus_wrapper
