// This file has been generated by Py++.

// (C) Christopher Woods, GPL >= 3 License

#ifndef Space_hpp__pyplusplus_wrapper
#define Space_hpp__pyplusplus_wrapper

void register_Space_class();

#endif//Space_hpp__pyplusplus_wrapper
