// This file has been generated by Py++.

// (C) Christopher Woods, GPL >= 3 License

#ifndef TransformedSpace_hpp__pyplusplus_wrapper
#define TransformedSpace_hpp__pyplusplus_wrapper

void register_TransformedSpace_class();

#endif//TransformedSpace_hpp__pyplusplus_wrapper
