// This file has been generated by Py++.

// (C) Christopher Woods, GPL >= 3 License

#ifndef AbsFromNumber_hpp__pyplusplus_wrapper
#define AbsFromNumber_hpp__pyplusplus_wrapper

void register_AbsFromNumber_class();

#endif//AbsFromNumber_hpp__pyplusplus_wrapper
