// This file has been generated by Py++.

// (C) Christopher Woods, GPL >= 3 License

#ifndef AmberParameters_hpp__pyplusplus_wrapper
#define AmberParameters_hpp__pyplusplus_wrapper

void register_AmberParameters_class();

#endif//AmberParameters_hpp__pyplusplus_wrapper
