// This file has been generated by Py++.

// (C) Christopher Woods, GPL >= 3 License

#ifndef AtomEditor_hpp__pyplusplus_wrapper
#define AtomEditor_hpp__pyplusplus_wrapper

void register_AtomEditor_class();

#endif//AtomEditor_hpp__pyplusplus_wrapper
