// This file has been generated by Py++.

// (C) Christopher Woods, GPL >= 3 License

#ifndef AtomElements_hpp__pyplusplus_wrapper
#define AtomElements_hpp__pyplusplus_wrapper

void register_AtomElements_class();

#endif//AtomElements_hpp__pyplusplus_wrapper
