// This file has been generated by Py++.

// (C) Christopher Woods, GPL >= 3 License

#ifndef AtomMapping_hpp__pyplusplus_wrapper
#define AtomMapping_hpp__pyplusplus_wrapper

void register_AtomMapping_class();

#endif//AtomMapping_hpp__pyplusplus_wrapper
