// This file has been generated by Py++.

// (C) Christopher Woods, GPL >= 3 License

#ifndef AtomCutting_hpp__pyplusplus_wrapper
#define AtomCutting_hpp__pyplusplus_wrapper

void register_AtomCutting_class();

#endif//AtomCutting_hpp__pyplusplus_wrapper
