// This file has been generated by Py++.

// (C) Christopher Woods, GPL >= 3 License

#include "boost/python.hpp"
#include "AtomNumMatcher.pypp.hpp"

namespace bp = boost::python;

#include "SireError/errors.h"

#include "SireMaths/vector.h"

#include "SireStream/datastream.h"

#include "SireUnits/units.h"

#include "atom.h"

#include "atomidentifier.h"

#include "atomidx.h"

#include "atommatcher.h"

#include "atommatchers.h"

#include "atomname.h"

#include "atomselection.h"

#include "evaluator.h"

#include "moleculeinfodata.h"

#include "moleculeview.h"

#include "mover.h"

#include "mover.hpp"

#include "selector.hpp"

#include "tostring.h"

#include "atommatchers.h"

SireMol::AtomNumMatcher __copy__(const SireMol::AtomNumMatcher &other){ return SireMol::AtomNumMatcher(other); }

#include "Helpers/copy.hpp"

#include "Qt/qdatastream.hpp"

#include "Helpers/str.hpp"

#include "Helpers/release_gil_policy.hpp"

void register_AtomNumMatcher_class(){

    { //::SireMol::AtomNumMatcher
        typedef bp::class_< SireMol::AtomNumMatcher, bp::bases< SireMol::AtomMatcher, SireBase::Property > > AtomNumMatcher_exposer_t;
        AtomNumMatcher_exposer_t AtomNumMatcher_exposer = AtomNumMatcher_exposer_t( "AtomNumMatcher", "This is a simple atom matcher that matches the atoms based\non their numbers, so the atom with number 1 in molinfo0 will\nbe matched to the atom with number 1 in molinfo1\n", bp::init< >("Constructor") );
        bp::scope AtomNumMatcher_scope( AtomNumMatcher_exposer );
        AtomNumMatcher_exposer.def( bp::init< SireMol::AtomNumMatcher const & >(( bp::arg("arg0") ), "Copy constructor") );
        AtomNumMatcher_exposer.def( bp::self != bp::self );
        { //::SireMol::AtomNumMatcher::operator=
        
            typedef ::SireMol::AtomNumMatcher & ( ::SireMol::AtomNumMatcher::*assign_function_type)( ::SireMol::AtomNumMatcher const & ) ;
            assign_function_type assign_function_value( &::SireMol::AtomNumMatcher::operator= );
            
            AtomNumMatcher_exposer.def( 
                "assign"
                , assign_function_value
                , ( bp::arg("other") )
                , bp::return_self< >()
                , "" );
        
        }
        AtomNumMatcher_exposer.def( bp::self == bp::self );
        { //::SireMol::AtomNumMatcher::toString
        
            typedef ::QString ( ::SireMol::AtomNumMatcher::*toString_function_type)(  ) const;
            toString_function_type toString_function_value( &::SireMol::AtomNumMatcher::toString );
            
            AtomNumMatcher_exposer.def( 
                "toString"
                , toString_function_value
                , bp::release_gil_policy()
                , "" );
        
        }
        { //::SireMol::AtomNumMatcher::typeName
        
            typedef char const * ( *typeName_function_type )(  );
            typeName_function_type typeName_function_value( &::SireMol::AtomNumMatcher::typeName );
            
            AtomNumMatcher_exposer.def( 
                "typeName"
                , typeName_function_value
                , bp::release_gil_policy()
                , "" );
        
        }
        { //::SireMol::AtomNumMatcher::what
        
            typedef char const * ( ::SireMol::AtomNumMatcher::*what_function_type)(  ) const;
            what_function_type what_function_value( &::SireMol::AtomNumMatcher::what );
            
            AtomNumMatcher_exposer.def( 
                "what"
                , what_function_value
                , bp::release_gil_policy()
                , "" );
        
        }
        AtomNumMatcher_exposer.staticmethod( "typeName" );
        AtomNumMatcher_exposer.def( "__copy__", &__copy__<SireMol::AtomNumMatcher>);
        AtomNumMatcher_exposer.def( "__deepcopy__", &__copy__<SireMol::AtomNumMatcher>);
        AtomNumMatcher_exposer.def( "clone", &__copy__<SireMol::AtomNumMatcher>);
        AtomNumMatcher_exposer.def( "__rlshift__", &__rlshift__QDataStream< ::SireMol::AtomNumMatcher >,
                            bp::return_internal_reference<1, bp::with_custodian_and_ward<1,2> >() );
        AtomNumMatcher_exposer.def( "__rrshift__", &__rrshift__QDataStream< ::SireMol::AtomNumMatcher >,
                            bp::return_internal_reference<1, bp::with_custodian_and_ward<1,2> >() );
        AtomNumMatcher_exposer.def_pickle(sire_pickle_suite< ::SireMol::AtomNumMatcher >());
        AtomNumMatcher_exposer.def( "__str__", &__str__< ::SireMol::AtomNumMatcher > );
        AtomNumMatcher_exposer.def( "__repr__", &__str__< ::SireMol::AtomNumMatcher > );
    }

}
