// This file has been generated by Py++.

// (C) Christopher Woods, GPL >= 3 License

#ifndef AtomPropertyList_hpp__pyplusplus_wrapper
#define AtomPropertyList_hpp__pyplusplus_wrapper

void register_AtomPropertyList_class();

#endif//AtomPropertyList_hpp__pyplusplus_wrapper
