// This file has been generated by Py++.

// (C) Christopher Woods, GPL >= 3 License

#ifndef AtomIntegerArrayProperty_hpp__pyplusplus_wrapper
#define AtomIntegerArrayProperty_hpp__pyplusplus_wrapper

void register_AtomIntegerArrayProperty_class();

#endif//AtomIntegerArrayProperty_hpp__pyplusplus_wrapper
