// This file has been generated by Py++.

// (C) Christopher Woods, GPL >= 3 License

#ifndef AtomMatch_hpp__pyplusplus_wrapper
#define AtomMatch_hpp__pyplusplus_wrapper

void register_AtomMatch_class();

#endif//AtomMatch_hpp__pyplusplus_wrapper
