// This file has been generated by Py++.

// (C) Christopher Woods, GPL >= 3 License

#ifndef AtomStringProperty_hpp__pyplusplus_wrapper
#define AtomStringProperty_hpp__pyplusplus_wrapper

void register_AtomStringProperty_class();

#endif//AtomStringProperty_hpp__pyplusplus_wrapper
