// This file has been generated by Py++.

// (C) Christopher Woods, GPL >= 3 License

#ifndef AtomID_hpp__pyplusplus_wrapper
#define AtomID_hpp__pyplusplus_wrapper

void register_AtomID_class();

#endif//AtomID_hpp__pyplusplus_wrapper
