// This file has been generated by Py++.

// (C) Christopher Woods, GPL >= 3 License

#ifndef AtomMatchM_hpp__pyplusplus_wrapper
#define AtomMatchM_hpp__pyplusplus_wrapper

void register_AtomMatchM_class();

#endif//AtomMatchM_hpp__pyplusplus_wrapper
