// This file has been generated by Py++.

// (C) Christopher Woods, GPL >= 3 License

#ifndef BeadProp_hpp__pyplusplus_wrapper
#define BeadProp_hpp__pyplusplus_wrapper

void register_BeadProp_class();

#endif//BeadProp_hpp__pyplusplus_wrapper
