// This file has been generated by Py++.

// (C) Christopher Woods, GPL >= 3 License

#ifndef BeadIntProperty_hpp__pyplusplus_wrapper
#define BeadIntProperty_hpp__pyplusplus_wrapper

void register_BeadIntProperty_class();

#endif//BeadIntProperty_hpp__pyplusplus_wrapper
