// This file has been generated by Py++.

// (C) Christopher Woods, GPL >= 3 License

#ifndef BeadFloatProperty_hpp__pyplusplus_wrapper
#define BeadFloatProperty_hpp__pyplusplus_wrapper

void register_BeadFloatProperty_class();

#endif//BeadFloatProperty_hpp__pyplusplus_wrapper
