// This file has been generated by Py++.

// (C) Christopher Woods, GPL >= 3 License

#ifndef BeadVariantProperty_hpp__pyplusplus_wrapper
#define BeadVariantProperty_hpp__pyplusplus_wrapper

void register_BeadVariantProperty_class();

#endif//BeadVariantProperty_hpp__pyplusplus_wrapper
