// This file has been generated by Py++.

// (C) Christopher Woods, GPL >= 3 License

#ifndef BondOrder_hpp__pyplusplus_wrapper
#define BondOrder_hpp__pyplusplus_wrapper

void register_BondOrder_class();

#endif//BondOrder_hpp__pyplusplus_wrapper
