// This file has been generated by Py++.

// (C) Christopher Woods, GPL >= 3 License

#ifndef CGChainID_hpp__pyplusplus_wrapper
#define CGChainID_hpp__pyplusplus_wrapper

void register_CGChainID_class();

#endif//CGChainID_hpp__pyplusplus_wrapper
