// This file has been generated by Py++.

// (C) Christopher Woods, GPL >= 3 License

#ifndef CGIntProperty_hpp__pyplusplus_wrapper
#define CGIntProperty_hpp__pyplusplus_wrapper

void register_CGIntProperty_class();

#endif//CGIntProperty_hpp__pyplusplus_wrapper
