// This file has been generated by Py++.

// (C) Christopher Woods, GPL >= 3 License

#ifndef CGPropertyProperty_hpp__pyplusplus_wrapper
#define CGPropertyProperty_hpp__pyplusplus_wrapper

void register_CGPropertyProperty_class();

#endif//CGPropertyProperty_hpp__pyplusplus_wrapper
