// This file has been generated by Py++.

// (C) Christopher Woods, GPL >= 3 License

#ifndef ChainIntProperty_hpp__pyplusplus_wrapper
#define ChainIntProperty_hpp__pyplusplus_wrapper

void register_ChainIntProperty_class();

#endif//ChainIntProperty_hpp__pyplusplus_wrapper
