// This file has been generated by Py++.

// (C) Christopher Woods, GPL >= 3 License

#ifndef EvaluatorM_hpp__pyplusplus_wrapper
#define EvaluatorM_hpp__pyplusplus_wrapper

void register_EvaluatorM_class();

#endif//EvaluatorM_hpp__pyplusplus_wrapper
