// This file has been generated by Py++.

// (C) Christopher Woods, GPL >= 3 License

#ifndef IDOrSet_MolID__hpp__pyplusplus_wrapper
#define IDOrSet_MolID__hpp__pyplusplus_wrapper

void register_IDOrSet_MolID__class();

#endif//IDOrSet_MolID__hpp__pyplusplus_wrapper
