// This file has been generated by Py++.

// (C) Christopher Woods, GPL >= 3 License

#ifndef IDOrSet_MGID__hpp__pyplusplus_wrapper
#define IDOrSet_MGID__hpp__pyplusplus_wrapper

void register_IDOrSet_MGID__class();

#endif//IDOrSet_MGID__hpp__pyplusplus_wrapper
