// This file has been generated by Py++.

// (C) Christopher Woods, GPL >= 3 License

#ifndef MGIdx_hpp__pyplusplus_wrapper
#define MGIdx_hpp__pyplusplus_wrapper

void register_MGIdx_class();

#endif//MGIdx_hpp__pyplusplus_wrapper
