// This file has been generated by Py++.

// (C) Christopher Woods, GPL >= 3 License

#ifndef MGName_hpp__pyplusplus_wrapper
#define MGName_hpp__pyplusplus_wrapper

void register_MGName_class();

#endif//MGName_hpp__pyplusplus_wrapper
