// This file has been generated by Py++.

// (C) Christopher Woods, GPL >= 3 License

#ifndef Mover_Atom__hpp__pyplusplus_wrapper
#define Mover_Atom__hpp__pyplusplus_wrapper

void register_Mover_Atom__class();

#endif//Mover_Atom__hpp__pyplusplus_wrapper
