// This file has been generated by Py++.

// (C) Christopher Woods, GPL >= 3 License

#ifndef NullGeometryPerturbation_hpp__pyplusplus_wrapper
#define NullGeometryPerturbation_hpp__pyplusplus_wrapper

void register_NullGeometryPerturbation_class();

#endif//NullGeometryPerturbation_hpp__pyplusplus_wrapper
