// This file has been generated by Py++.

// (C) Christopher Woods, GPL >= 3 License

#ifndef ResID_hpp__pyplusplus_wrapper
#define ResID_hpp__pyplusplus_wrapper

void register_ResID_class();

#endif//ResID_hpp__pyplusplus_wrapper
