// This file has been generated by Py++.

// (C) Christopher Woods, GPL >= 3 License

#ifndef ResName_hpp__pyplusplus_wrapper
#define ResName_hpp__pyplusplus_wrapper

void register_ResName_class();

#endif//ResName_hpp__pyplusplus_wrapper
