// This file has been generated by Py++.

// (C) Christopher Woods, GPL >= 3 License

#ifndef ResProp_hpp__pyplusplus_wrapper
#define ResProp_hpp__pyplusplus_wrapper

void register_ResProp_class();

#endif//ResProp_hpp__pyplusplus_wrapper
