// This file has been generated by Py++.

// (C) Christopher Woods, GPL >= 3 License

#ifndef ResStringProperty_hpp__pyplusplus_wrapper
#define ResStringProperty_hpp__pyplusplus_wrapper

void register_ResStringProperty_class();

#endif//ResStringProperty_hpp__pyplusplus_wrapper
