// This file has been generated by Py++.

// (C) Christopher Woods, GPL >= 3 License

#ifndef SegAtomID_hpp__pyplusplus_wrapper
#define SegAtomID_hpp__pyplusplus_wrapper

void register_SegAtomID_class();

#endif//SegAtomID_hpp__pyplusplus_wrapper
