// This file has been generated by Py++.

// (C) Christopher Woods, GPL >= 3 License

#ifndef Stereochemistry_hpp__pyplusplus_wrapper
#define Stereochemistry_hpp__pyplusplus_wrapper

void register_Stereochemistry_class();

#endif//Stereochemistry_hpp__pyplusplus_wrapper
