// This file has been generated by Py++.

// (C) Christopher Woods, GPL >= 3 License

#ifndef Node_hpp__pyplusplus_wrapper
#define Node_hpp__pyplusplus_wrapper

void register_Node_class();

#endif//Node_hpp__pyplusplus_wrapper
