// This file has been generated by Py++.

// (C) Christopher Woods, GPL >= 3 License

#ifndef Nodes_hpp__pyplusplus_wrapper
#define Nodes_hpp__pyplusplus_wrapper

void register_Nodes_class();

#endif//Nodes_hpp__pyplusplus_wrapper
