// This file has been generated by Py++.

// (C) Christopher Woods, GPL >= 3 License

#ifndef ComponentGradients_hpp__pyplusplus_wrapper
#define ComponentGradients_hpp__pyplusplus_wrapper

void register_ComponentGradients_class();

#endif//ComponentGradients_hpp__pyplusplus_wrapper
