// This file has been generated by Py++.

// (C) Christopher Woods, GPL >= 3 License

#ifndef AmberDihPart_hpp__pyplusplus_wrapper
#define AmberDihPart_hpp__pyplusplus_wrapper

void register_AmberDihPart_class();

#endif//AmberDihPart_hpp__pyplusplus_wrapper
