// This file has been generated by Py++.

// (C) Christopher Woods, GPL >= 3 License

#ifndef AngleRestraint_hpp__pyplusplus_wrapper
#define AngleRestraint_hpp__pyplusplus_wrapper

void register_AngleRestraint_class();

#endif//AngleRestraint_hpp__pyplusplus_wrapper
