// This file has been generated by Py++.

// (C) Christopher Woods, GPL >= 3 License

#ifndef AtomPairs_LJScaleFactor__hpp__pyplusplus_wrapper
#define AtomPairs_LJScaleFactor__hpp__pyplusplus_wrapper

void register_AtomPairs_LJScaleFactor__class();

#endif//AtomPairs_LJScaleFactor__hpp__pyplusplus_wrapper
