// This file has been generated by Py++.

// (C) Christopher Woods, GPL >= 3 License

#ifndef AtomFunction_hpp__pyplusplus_wrapper
#define AtomFunction_hpp__pyplusplus_wrapper

void register_AtomFunction_class();

#endif//AtomFunction_hpp__pyplusplus_wrapper
