// This file has been generated by Py++.

// (C) Christopher Woods, GPL >= 3 License

#ifndef AtomPairs_CoulombScaleFactor__hpp__pyplusplus_wrapper
#define AtomPairs_CoulombScaleFactor__hpp__pyplusplus_wrapper

void register_AtomPairs_CoulombScaleFactor__class();

#endif//AtomPairs_CoulombScaleFactor__hpp__pyplusplus_wrapper
