// This file has been generated by Py++.

// (C) Christopher Woods, GPL >= 3 License

#ifndef AtomFunctions_hpp__pyplusplus_wrapper
#define AtomFunctions_hpp__pyplusplus_wrapper

void register_AtomFunctions_class();

#endif//AtomFunctions_hpp__pyplusplus_wrapper
