// This file has been generated by Py++.

// (C) Christopher Woods, GPL >= 3 License

#ifndef BondParameterName_hpp__pyplusplus_wrapper
#define BondParameterName_hpp__pyplusplus_wrapper

void register_BondParameterName_class();

#endif//BondParameterName_hpp__pyplusplus_wrapper
