// This file has been generated by Py++.

// (C) Christopher Woods, GPL >= 3 License

#include "boost/python.hpp"
#include "Helpers/clone_const_reference.hpp"
#include "BondRestraints.pypp.hpp"

namespace bp = boost::python;

#include "SireError/errors.h"

#include "SireID/index.h"

#include "SireStream/datastream.h"

#include "SireStream/shareddatastream.h"

#include "SireUnits/units.h"

#include "bondrestraints.h"

#include <QDebug>

#include "bondrestraints.h"

SireMM::BondRestraints __copy__(const SireMM::BondRestraints &other){ return SireMM::BondRestraints(other); }

#include "Helpers/copy.hpp"

#include "Qt/qdatastream.hpp"

#include "Helpers/str.hpp"

#include "Helpers/release_gil_policy.hpp"

#include "Helpers/len.hpp"

void register_BondRestraints_class(){

    { //::SireMM::BondRestraints
        typedef bp::class_< SireMM::BondRestraints, bp::bases< SireMM::Restraints, SireBase::Property > > BondRestraints_exposer_t;
        BondRestraints_exposer_t BondRestraints_exposer = BondRestraints_exposer_t( "BondRestraints", "This class provides the information for a collection of bond\nrestraints that can be added to a collection of molecues. Each\nrestraint can act on a pair of particles or a pair of the\ncentroids of two collections of particles.\nThe restaints are spherically symmetric, and\nare simple harmonic potentials\n", bp::init< >("Null constructor") );
        bp::scope BondRestraints_scope( BondRestraints_exposer );
        BondRestraints_exposer.def( bp::init< QString const & >(( bp::arg("name") ), "") );
        BondRestraints_exposer.def( bp::init< SireMM::BondRestraint const & >(( bp::arg("restraint") ), "") );
        BondRestraints_exposer.def( bp::init< QList< SireMM::BondRestraint > const & >(( bp::arg("restraints") ), "") );
        BondRestraints_exposer.def( bp::init< QString const &, SireMM::BondRestraint const & >(( bp::arg("name"), bp::arg("restraint") ), "") );
        BondRestraints_exposer.def( bp::init< QString const &, QList< SireMM::BondRestraint > const & >(( bp::arg("name"), bp::arg("restraints") ), "") );
        BondRestraints_exposer.def( bp::init< SireMM::BondRestraints const & >(( bp::arg("other") ), "") );
        { //::SireMM::BondRestraints::add
        
            typedef void ( ::SireMM::BondRestraints::*add_function_type)( ::SireMM::BondRestraint const & ) ;
            add_function_type add_function_value( &::SireMM::BondRestraints::add );
            
            BondRestraints_exposer.def( 
                "add"
                , add_function_value
                , ( bp::arg("restraint") )
                , bp::release_gil_policy()
                , "Add a restraint onto the list" );
        
        }
        { //::SireMM::BondRestraints::add
        
            typedef void ( ::SireMM::BondRestraints::*add_function_type)( ::SireMM::BondRestraints const & ) ;
            add_function_type add_function_value( &::SireMM::BondRestraints::add );
            
            BondRestraints_exposer.def( 
                "add"
                , add_function_value
                , ( bp::arg("restraints") )
                , bp::release_gil_policy()
                , "Add a restraint onto the list" );
        
        }
        { //::SireMM::BondRestraints::at
        
            typedef ::SireMM::BondRestraint const & ( ::SireMM::BondRestraints::*at_function_type)( int ) const;
            at_function_type at_function_value( &::SireMM::BondRestraints::at );
            
            BondRestraints_exposer.def( 
                "at"
                , at_function_value
                , ( bp::arg("i") )
                , bp::return_value_policy<bp::clone_const_reference, bp::release_gil_policy>()
                , "Return the ith restraint" );
        
        }
        { //::SireMM::BondRestraints::atomRestraints
        
            typedef ::QList< SireMM::BondRestraint > ( ::SireMM::BondRestraints::*atomRestraints_function_type)(  ) const;
            atomRestraints_function_type atomRestraints_function_value( &::SireMM::BondRestraints::atomRestraints );
            
            BondRestraints_exposer.def( 
                "atomRestraints"
                , atomRestraints_function_value
                , bp::release_gil_policy()
                , "Return all of the atom restraints" );
        
        }
        { //::SireMM::BondRestraints::centroidRestraints
        
            typedef ::QList< SireMM::BondRestraint > ( ::SireMM::BondRestraints::*centroidRestraints_function_type)(  ) const;
            centroidRestraints_function_type centroidRestraints_function_value( &::SireMM::BondRestraints::centroidRestraints );
            
            BondRestraints_exposer.def( 
                "centroidRestraints"
                , centroidRestraints_function_value
                , bp::release_gil_policy()
                , "Return all of the centroid restraints" );
        
        }
        { //::SireMM::BondRestraints::count
        
            typedef int ( ::SireMM::BondRestraints::*count_function_type)(  ) const;
            count_function_type count_function_value( &::SireMM::BondRestraints::count );
            
            BondRestraints_exposer.def( 
                "count"
                , count_function_value
                , bp::release_gil_policy()
                , "Return the number of restraints" );
        
        }
        { //::SireMM::BondRestraints::usesPbc
        
            typedef bool ( ::SireMM::BondRestraints::*usesPbc_function_type)(  ) const;
            usesPbc_function_type usesPbc_function_value( &::SireMM::BondRestraints::usesPbc );
            
            BondRestraints_exposer.def( 
                "usesPbc"
                , usesPbc_function_value
                , bp::release_gil_policy()
                , "Return whether or not periodic boundary conditions are to be used" );
        
        }
        { //::SireMM::BondRestraints::hasAtomRestraints
        
            typedef bool ( ::SireMM::BondRestraints::*hasAtomRestraints_function_type)(  ) const;
            hasAtomRestraints_function_type hasAtomRestraints_function_value( &::SireMM::BondRestraints::hasAtomRestraints );
            
            BondRestraints_exposer.def( 
                "hasAtomRestraints"
                , hasAtomRestraints_function_value
                , bp::release_gil_policy()
                , "Return whether or not there are any atom restraints" );
        
        }
        { //::SireMM::BondRestraints::hasCentroidRestraints
        
            typedef bool ( ::SireMM::BondRestraints::*hasCentroidRestraints_function_type)(  ) const;
            hasCentroidRestraints_function_type hasCentroidRestraints_function_value( &::SireMM::BondRestraints::hasCentroidRestraints );
            
            BondRestraints_exposer.def( 
                "hasCentroidRestraints"
                , hasCentroidRestraints_function_value
                , bp::release_gil_policy()
                , "Return whether or not there are any centroid restraints" );
        
        }
        { //::SireMM::BondRestraints::isEmpty
        
            typedef bool ( ::SireMM::BondRestraints::*isEmpty_function_type)(  ) const;
            isEmpty_function_type isEmpty_function_value( &::SireMM::BondRestraints::isEmpty );
            
            BondRestraints_exposer.def( 
                "isEmpty"
                , isEmpty_function_value
                , bp::release_gil_policy()
                , "Return whether or not this is empty" );
        
        }
        { //::SireMM::BondRestraints::isNull
        
            typedef bool ( ::SireMM::BondRestraints::*isNull_function_type)(  ) const;
            isNull_function_type isNull_function_value( &::SireMM::BondRestraints::isNull );
            
            BondRestraints_exposer.def( 
                "isNull"
                , isNull_function_value
                , bp::release_gil_policy()
                , "Return whether or not this is empty" );
        
        }
        { //::SireMM::BondRestraints::nAtomRestraints
        
            typedef int ( ::SireMM::BondRestraints::*nAtomRestraints_function_type)(  ) const;
            nAtomRestraints_function_type nAtomRestraints_function_value( &::SireMM::BondRestraints::nAtomRestraints );
            
            BondRestraints_exposer.def( 
                "nAtomRestraints"
                , nAtomRestraints_function_value
                , bp::release_gil_policy()
                , "Return the number of atom restraints" );
        
        }
        { //::SireMM::BondRestraints::nCentroidRestraints
        
            typedef int ( ::SireMM::BondRestraints::*nCentroidRestraints_function_type)(  ) const;
            nCentroidRestraints_function_type nCentroidRestraints_function_value( &::SireMM::BondRestraints::nCentroidRestraints );
            
            BondRestraints_exposer.def( 
                "nCentroidRestraints"
                , nCentroidRestraints_function_value
                , bp::release_gil_policy()
                , "Return the number of centroid restraints" );
        
        }
        { //::SireMM::BondRestraints::nRestraints
        
            typedef int ( ::SireMM::BondRestraints::*nRestraints_function_type)(  ) const;
            nRestraints_function_type nRestraints_function_value( &::SireMM::BondRestraints::nRestraints );
            
            BondRestraints_exposer.def( 
                "nRestraints"
                , nRestraints_function_value
                , bp::release_gil_policy()
                , "Return the number of restraints" );
        
        }
        BondRestraints_exposer.def( bp::self != bp::self );
        BondRestraints_exposer.def( bp::self + bp::other< SireMM::BondRestraint >() );
        BondRestraints_exposer.def( bp::self + bp::self );
        { //::SireMM::BondRestraints::operator=
        
            typedef ::SireMM::BondRestraints & ( ::SireMM::BondRestraints::*assign_function_type)( ::SireMM::BondRestraints const & ) ;
            assign_function_type assign_function_value( &::SireMM::BondRestraints::operator= );
            
            BondRestraints_exposer.def( 
                "assign"
                , assign_function_value
                , ( bp::arg("other") )
                , bp::return_self< >()
                , "" );
        
        }
        BondRestraints_exposer.def( bp::self == bp::self );
        { //::SireMM::BondRestraints::operator[]
        
            typedef ::SireMM::BondRestraint const & ( ::SireMM::BondRestraints::*__getitem___function_type)( int ) const;
            __getitem___function_type __getitem___function_value( &::SireMM::BondRestraints::operator[] );
            
            BondRestraints_exposer.def( 
                "__getitem__"
                , __getitem___function_value
                , ( bp::arg("i") )
                , bp::return_value_policy<bp::clone_const_reference, bp::release_gil_policy>()
                , "" );
        
        }
        { //::SireMM::BondRestraints::restraints
        
            typedef ::QList< SireMM::BondRestraint > ( ::SireMM::BondRestraints::*restraints_function_type)(  ) const;
            restraints_function_type restraints_function_value( &::SireMM::BondRestraints::restraints );
            
            BondRestraints_exposer.def( 
                "restraints"
                , restraints_function_value
                , bp::release_gil_policy()
                , "Return all of the restraints" );
        
        }
        { //::SireMM::BondRestraints::setUsesPbc
        
            typedef void ( ::SireMM::BondRestraints::*setUsesPbc_function_type)( bool ) ;
            setUsesPbc_function_type setUsesPbc_function_value( &::SireMM::BondRestraints::setUsesPbc );
            
            BondRestraints_exposer.def( 
                "setUsesPbc"
                , setUsesPbc_function_value
                , ( bp::arg("use_pbc") )
                , bp::release_gil_policy()
                , "Set whether or not periodic boundary conditions are to be used" );
        
        }
        { //::SireMM::BondRestraints::size
        
            typedef int ( ::SireMM::BondRestraints::*size_function_type)(  ) const;
            size_function_type size_function_value( &::SireMM::BondRestraints::size );
            
            BondRestraints_exposer.def( 
                "size"
                , size_function_value
                , bp::release_gil_policy()
                , "Return the number of restraints" );
        
        }
        { //::SireMM::BondRestraints::toString
        
            typedef ::QString ( ::SireMM::BondRestraints::*toString_function_type)(  ) const;
            toString_function_type toString_function_value( &::SireMM::BondRestraints::toString );
            
            BondRestraints_exposer.def( 
                "toString"
                , toString_function_value
                , bp::release_gil_policy()
                , "" );
        
        }
        { //::SireMM::BondRestraints::typeName
        
            typedef char const * ( *typeName_function_type )(  );
            typeName_function_type typeName_function_value( &::SireMM::BondRestraints::typeName );
            
            BondRestraints_exposer.def( 
                "typeName"
                , typeName_function_value
                , bp::release_gil_policy()
                , "" );
        
        }
        { //::SireMM::BondRestraints::what
        
            typedef char const * ( ::SireMM::BondRestraints::*what_function_type)(  ) const;
            what_function_type what_function_value( &::SireMM::BondRestraints::what );
            
            BondRestraints_exposer.def( 
                "what"
                , what_function_value
                , bp::release_gil_policy()
                , "" );
        
        }
        BondRestraints_exposer.staticmethod( "typeName" );
        BondRestraints_exposer.def( "__copy__", &__copy__<SireMM::BondRestraints>);
        BondRestraints_exposer.def( "__deepcopy__", &__copy__<SireMM::BondRestraints>);
        BondRestraints_exposer.def( "clone", &__copy__<SireMM::BondRestraints>);
        BondRestraints_exposer.def( "__rlshift__", &__rlshift__QDataStream< ::SireMM::BondRestraints >,
                            bp::return_internal_reference<1, bp::with_custodian_and_ward<1,2> >() );
        BondRestraints_exposer.def( "__rrshift__", &__rrshift__QDataStream< ::SireMM::BondRestraints >,
                            bp::return_internal_reference<1, bp::with_custodian_and_ward<1,2> >() );
        BondRestraints_exposer.def_pickle(sire_pickle_suite< ::SireMM::BondRestraints >());
        BondRestraints_exposer.def( "__str__", &__str__< ::SireMM::BondRestraints > );
        BondRestraints_exposer.def( "__repr__", &__str__< ::SireMM::BondRestraints > );
        BondRestraints_exposer.def( "__len__", &__len_size< ::SireMM::BondRestraints > );
    }

}
