// This file has been generated by Py++.

// (C) Christopher Woods, GPL >= 3 License

#ifndef BondRestraint_hpp__pyplusplus_wrapper
#define BondRestraint_hpp__pyplusplus_wrapper

void register_BondRestraint_class();

#endif//BondRestraint_hpp__pyplusplus_wrapper
