// This file has been generated by Py++.

// (C) Christopher Woods, GPL >= 3 License

#ifndef BoreschRestraints_hpp__pyplusplus_wrapper
#define BoreschRestraints_hpp__pyplusplus_wrapper

void register_BoreschRestraints_class();

#endif//BoreschRestraints_hpp__pyplusplus_wrapper
