// This file has been generated by Py++.

// (C) Christopher Woods, GPL >= 3 License

#ifndef CHARMMSwitchingFunction_hpp__pyplusplus_wrapper
#define CHARMMSwitchingFunction_hpp__pyplusplus_wrapper

void register_CHARMMSwitchingFunction_class();

#endif//CHARMMSwitchingFunction_hpp__pyplusplus_wrapper
