// This file has been generated by Py++.

// (C) Christopher Woods, GPL >= 3 License

#ifndef CLJAtoms_hpp__pyplusplus_wrapper
#define CLJAtoms_hpp__pyplusplus_wrapper

void register_CLJAtoms_class();

#endif//CLJAtoms_hpp__pyplusplus_wrapper
