// This file has been generated by Py++.

// (C) Christopher Woods, GPL >= 3 License

#ifndef CLJBoxIndex_hpp__pyplusplus_wrapper
#define CLJBoxIndex_hpp__pyplusplus_wrapper

void register_CLJBoxIndex_class();

#endif//CLJBoxIndex_hpp__pyplusplus_wrapper
