// This file has been generated by Py++.

// (C) Christopher Woods, GPL >= 3 License

#ifndef CLJFunction_hpp__pyplusplus_wrapper
#define CLJFunction_hpp__pyplusplus_wrapper

void register_CLJFunction_class();

#endif//CLJFunction_hpp__pyplusplus_wrapper
