// This file has been generated by Py++.

// (C) Christopher Woods, GPL >= 3 License

#ifndef CLJGrid_hpp__pyplusplus_wrapper
#define CLJGrid_hpp__pyplusplus_wrapper

void register_CLJGrid_class();

#endif//CLJGrid_hpp__pyplusplus_wrapper
