// This file has been generated by Py++.

// (C) Christopher Woods, GPL >= 3 License

#ifndef CLJGroup_hpp__pyplusplus_wrapper
#define CLJGroup_hpp__pyplusplus_wrapper

void register_CLJGroup_class();

#endif//CLJGroup_hpp__pyplusplus_wrapper
