// This file has been generated by Py++.

// (C) Christopher Woods, GPL >= 3 License

#ifndef CLJNBPairs_hpp__pyplusplus_wrapper
#define CLJNBPairs_hpp__pyplusplus_wrapper

void register_CLJNBPairs_class();

#endif//CLJNBPairs_hpp__pyplusplus_wrapper
