// This file has been generated by Py++.

// (C) Christopher Woods, GPL >= 3 License

#ifndef CLJParameterNames3D_hpp__pyplusplus_wrapper
#define CLJParameterNames3D_hpp__pyplusplus_wrapper

void register_CLJParameterNames3D_class();

#endif//CLJParameterNames3D_hpp__pyplusplus_wrapper
