// This file has been generated by Py++.

// (C) Christopher Woods, GPL >= 3 License

#ifndef CLJPotentialInterface_InterCLJPotential__hpp__pyplusplus_wrapper
#define CLJPotentialInterface_InterCLJPotential__hpp__pyplusplus_wrapper

void register_CLJPotentialInterface_InterCLJPotential__class();

#endif//CLJPotentialInterface_InterCLJPotential__hpp__pyplusplus_wrapper
