// This file has been generated by Py++.

// (C) Christopher Woods, GPL >= 3 License

#ifndef CMAPFunction_hpp__pyplusplus_wrapper
#define CMAPFunction_hpp__pyplusplus_wrapper

void register_CMAPFunction_class();

#endif//CMAPFunction_hpp__pyplusplus_wrapper
