// This file has been generated by Py++.

// (C) Christopher Woods, GPL >= 3 License

#ifndef CoulombNBPairs_hpp__pyplusplus_wrapper
#define CoulombNBPairs_hpp__pyplusplus_wrapper

void register_CoulombNBPairs_class();

#endif//CoulombNBPairs_hpp__pyplusplus_wrapper
