// This file has been generated by Py++.

// (C) Christopher Woods, GPL >= 3 License

#ifndef DihedralComponent_hpp__pyplusplus_wrapper
#define DihedralComponent_hpp__pyplusplus_wrapper

void register_DihedralComponent_class();

#endif//DihedralComponent_hpp__pyplusplus_wrapper
