// This file has been generated by Py++.

// (C) Christopher Woods, GPL >= 3 License

#ifndef FourAtomFunction_hpp__pyplusplus_wrapper
#define FourAtomFunction_hpp__pyplusplus_wrapper

void register_FourAtomFunction_class();

#endif//FourAtomFunction_hpp__pyplusplus_wrapper
