// This file has been generated by Py++.

// (C) Christopher Woods, GPL >= 3 License

#ifndef InterCLJFFBase_hpp__pyplusplus_wrapper
#define InterCLJFFBase_hpp__pyplusplus_wrapper

void register_InterCLJFFBase_class();

#endif//InterCLJFFBase_hpp__pyplusplus_wrapper
