// This file has been generated by Py++.

// (C) Christopher Woods, GPL >= 3 License

#ifndef InternalComponent_hpp__pyplusplus_wrapper
#define InternalComponent_hpp__pyplusplus_wrapper

void register_InternalComponent_class();

#endif//InternalComponent_hpp__pyplusplus_wrapper
