// This file has been generated by Py++.

// (C) Christopher Woods, GPL >= 3 License

#ifndef InterCoulombFF_hpp__pyplusplus_wrapper
#define InterCoulombFF_hpp__pyplusplus_wrapper

void register_InterCoulombFF_class();

#endif//InterCoulombFF_hpp__pyplusplus_wrapper
