// This file has been generated by Py++.

// (C) Christopher Woods, GPL >= 3 License

#ifndef InterGroupCLJFF_hpp__pyplusplus_wrapper
#define InterGroupCLJFF_hpp__pyplusplus_wrapper

void register_InterGroupCLJFF_class();

#endif//InterGroupCLJFF_hpp__pyplusplus_wrapper
