// This file has been generated by Py++.

// (C) Christopher Woods, GPL >= 3 License

#ifndef IntraGroupSoftCLJFFBase_hpp__pyplusplus_wrapper
#define IntraGroupSoftCLJFFBase_hpp__pyplusplus_wrapper

void register_IntraGroupSoftCLJFFBase_class();

#endif//IntraGroupSoftCLJFFBase_hpp__pyplusplus_wrapper
