// This file has been generated by Py++.

// (C) Christopher Woods, GPL >= 3 License

#ifndef IntraGroupLJFF_hpp__pyplusplus_wrapper
#define IntraGroupLJFF_hpp__pyplusplus_wrapper

void register_IntraGroupLJFF_class();

#endif//IntraGroupLJFF_hpp__pyplusplus_wrapper
