// This file has been generated by Py++.

// (C) Christopher Woods, GPL >= 3 License

#ifndef IntraCLJFFBase_hpp__pyplusplus_wrapper
#define IntraCLJFFBase_hpp__pyplusplus_wrapper

void register_IntraCLJFFBase_class();

#endif//IntraCLJFFBase_hpp__pyplusplus_wrapper
