// This file has been generated by Py++.

// (C) Christopher Woods, GPL >= 3 License

#ifndef IntraFF_hpp__pyplusplus_wrapper
#define IntraFF_hpp__pyplusplus_wrapper

void register_IntraFF_class();

#endif//IntraFF_hpp__pyplusplus_wrapper
