// This file has been generated by Py++.

// (C) Christopher Woods, GPL >= 3 License

#include "boost/python.hpp"
#include "InverseBondRestraint.pypp.hpp"

namespace bp = boost::python;

#include "SireError/errors.h"

#include "SireID/index.h"

#include "SireStream/datastream.h"

#include "SireStream/shareddatastream.h"

#include "SireUnits/units.h"

#include "inversebondrestraints.h"

#include <QDebug>

#include "inversebondrestraints.h"

SireMM::InverseBondRestraint __copy__(const SireMM::InverseBondRestraint &other){ return SireMM::InverseBondRestraint(other); }

#include "Helpers/copy.hpp"

#include "Qt/qdatastream.hpp"

#include "Helpers/str.hpp"

#include "Helpers/release_gil_policy.hpp"

void register_InverseBondRestraint_class(){

    { //::SireMM::InverseBondRestraint
        typedef bp::class_< SireMM::InverseBondRestraint, bp::bases< SireBase::Property > > InverseBondRestraint_exposer_t;
        InverseBondRestraint_exposer_t InverseBondRestraint_exposer = InverseBondRestraint_exposer_t( "InverseBondRestraint", "This class represents a single inverse bond restraint between any two\natoms in a system (or between the centroids of any two groups\nof atoms in a system)\n", bp::init< >("Null constructor") );
        bp::scope InverseBondRestraint_scope( InverseBondRestraint_exposer );
        InverseBondRestraint_exposer.def( bp::init< qint64, qint64, SireUnits::Dimension::HarmonicBondConstant const &, SireUnits::Dimension::Length const & >(( bp::arg("atom0"), bp::arg("atom1"), bp::arg("k"), bp::arg("r0") ), "Construct to restrain the atom at index atom to the specified position\n  using the specified force constant and flat-bottom well-width\n") );
        InverseBondRestraint_exposer.def( bp::init< QList< long long > const &, QList< long long > const &, SireUnits::Dimension::HarmonicBondConstant const &, SireUnits::Dimension::Length const & >(( bp::arg("atoms0"), bp::arg("atoms1"), bp::arg("k"), bp::arg("r0") ), "Construct to restrain the centroid of the atoms whose indicies are\n  in atoms to the specified position using the specified force constant\n  and flat-bottom well width\n") );
        InverseBondRestraint_exposer.def( bp::init< SireMM::InverseBondRestraint const & >(( bp::arg("other") ), "Copy constructor") );
        { //::SireMM::InverseBondRestraint::atom0
        
            typedef ::qint64 ( ::SireMM::InverseBondRestraint::*atom0_function_type)(  ) const;
            atom0_function_type atom0_function_value( &::SireMM::InverseBondRestraint::atom0 );
            
            InverseBondRestraint_exposer.def( 
                "atom0"
                , atom0_function_value
                , bp::release_gil_policy()
                , "Return the index of the atom if this is a single-atom restraint" );
        
        }
        { //::SireMM::InverseBondRestraint::atom1
        
            typedef ::qint64 ( ::SireMM::InverseBondRestraint::*atom1_function_type)(  ) const;
            atom1_function_type atom1_function_value( &::SireMM::InverseBondRestraint::atom1 );
            
            InverseBondRestraint_exposer.def( 
                "atom1"
                , atom1_function_value
                , bp::release_gil_policy()
                , "Return the index of the atom if this is a single-atom restraint" );
        
        }
        { //::SireMM::InverseBondRestraint::atoms0
        
            typedef ::QVector< long long > ( ::SireMM::InverseBondRestraint::*atoms0_function_type)(  ) const;
            atoms0_function_type atoms0_function_value( &::SireMM::InverseBondRestraint::atoms0 );
            
            InverseBondRestraint_exposer.def( 
                "atoms0"
                , atoms0_function_value
                , bp::release_gil_policy()
                , "Return the indexes of the atoms whose centroid is to be restrained" );
        
        }
        { //::SireMM::InverseBondRestraint::atoms1
        
            typedef ::QVector< long long > ( ::SireMM::InverseBondRestraint::*atoms1_function_type)(  ) const;
            atoms1_function_type atoms1_function_value( &::SireMM::InverseBondRestraint::atoms1 );
            
            InverseBondRestraint_exposer.def( 
                "atoms1"
                , atoms1_function_value
                , bp::release_gil_policy()
                , "Return the indexes of the atoms whose centroid is to be restrained" );
        
        }
        { //::SireMM::InverseBondRestraint::isAtomRestraint
        
            typedef bool ( ::SireMM::InverseBondRestraint::*isAtomRestraint_function_type)(  ) const;
            isAtomRestraint_function_type isAtomRestraint_function_value( &::SireMM::InverseBondRestraint::isAtomRestraint );
            
            InverseBondRestraint_exposer.def( 
                "isAtomRestraint"
                , isAtomRestraint_function_value
                , bp::release_gil_policy()
                , "Return whether this is a single-atom restraint" );
        
        }
        { //::SireMM::InverseBondRestraint::isCentroidRestraint
        
            typedef bool ( ::SireMM::InverseBondRestraint::*isCentroidRestraint_function_type)(  ) const;
            isCentroidRestraint_function_type isCentroidRestraint_function_value( &::SireMM::InverseBondRestraint::isCentroidRestraint );
            
            InverseBondRestraint_exposer.def( 
                "isCentroidRestraint"
                , isCentroidRestraint_function_value
                , bp::release_gil_policy()
                , "Return whether this restraint acts on the centroid of a group\n  of atoms" );
        
        }
        { //::SireMM::InverseBondRestraint::isNull
        
            typedef bool ( ::SireMM::InverseBondRestraint::*isNull_function_type)(  ) const;
            isNull_function_type isNull_function_value( &::SireMM::InverseBondRestraint::isNull );
            
            InverseBondRestraint_exposer.def( 
                "isNull"
                , isNull_function_value
                , bp::release_gil_policy()
                , "" );
        
        }
        { //::SireMM::InverseBondRestraint::k
        
            typedef ::SireUnits::Dimension::HarmonicBondConstant ( ::SireMM::InverseBondRestraint::*k_function_type)(  ) const;
            k_function_type k_function_value( &::SireMM::InverseBondRestraint::k );
            
            InverseBondRestraint_exposer.def( 
                "k"
                , k_function_value
                , bp::release_gil_policy()
                , "Return the force constant for the restraint" );
        
        }
        InverseBondRestraint_exposer.def( bp::self != bp::self );
        InverseBondRestraint_exposer.def( bp::self + bp::self );
        InverseBondRestraint_exposer.def( bp::self + bp::other< SireMM::InverseBondRestraints >() );
        { //::SireMM::InverseBondRestraint::operator=
        
            typedef ::SireMM::InverseBondRestraint & ( ::SireMM::InverseBondRestraint::*assign_function_type)( ::SireMM::InverseBondRestraint const & ) ;
            assign_function_type assign_function_value( &::SireMM::InverseBondRestraint::operator= );
            
            InverseBondRestraint_exposer.def( 
                "assign"
                , assign_function_value
                , ( bp::arg("other") )
                , bp::return_self< >()
                , "" );
        
        }
        InverseBondRestraint_exposer.def( bp::self == bp::self );
        { //::SireMM::InverseBondRestraint::r0
        
            typedef ::SireUnits::Dimension::Length ( ::SireMM::InverseBondRestraint::*r0_function_type)(  ) const;
            r0_function_type r0_function_value( &::SireMM::InverseBondRestraint::r0 );
            
            InverseBondRestraint_exposer.def( 
                "r0"
                , r0_function_value
                , bp::release_gil_policy()
                , "Return the width of the harmonic bond." );
        
        }
        { //::SireMM::InverseBondRestraint::toString
        
            typedef ::QString ( ::SireMM::InverseBondRestraint::*toString_function_type)(  ) const;
            toString_function_type toString_function_value( &::SireMM::InverseBondRestraint::toString );
            
            InverseBondRestraint_exposer.def( 
                "toString"
                , toString_function_value
                , bp::release_gil_policy()
                , "" );
        
        }
        { //::SireMM::InverseBondRestraint::typeName
        
            typedef char const * ( *typeName_function_type )(  );
            typeName_function_type typeName_function_value( &::SireMM::InverseBondRestraint::typeName );
            
            InverseBondRestraint_exposer.def( 
                "typeName"
                , typeName_function_value
                , bp::release_gil_policy()
                , "" );
        
        }
        { //::SireMM::InverseBondRestraint::what
        
            typedef char const * ( ::SireMM::InverseBondRestraint::*what_function_type)(  ) const;
            what_function_type what_function_value( &::SireMM::InverseBondRestraint::what );
            
            InverseBondRestraint_exposer.def( 
                "what"
                , what_function_value
                , bp::release_gil_policy()
                , "" );
        
        }
        InverseBondRestraint_exposer.staticmethod( "typeName" );
        InverseBondRestraint_exposer.def( "__copy__", &__copy__<SireMM::InverseBondRestraint>);
        InverseBondRestraint_exposer.def( "__deepcopy__", &__copy__<SireMM::InverseBondRestraint>);
        InverseBondRestraint_exposer.def( "clone", &__copy__<SireMM::InverseBondRestraint>);
        InverseBondRestraint_exposer.def( "__rlshift__", &__rlshift__QDataStream< ::SireMM::InverseBondRestraint >,
                            bp::return_internal_reference<1, bp::with_custodian_and_ward<1,2> >() );
        InverseBondRestraint_exposer.def( "__rrshift__", &__rrshift__QDataStream< ::SireMM::InverseBondRestraint >,
                            bp::return_internal_reference<1, bp::with_custodian_and_ward<1,2> >() );
        InverseBondRestraint_exposer.def_pickle(sire_pickle_suite< ::SireMM::InverseBondRestraint >());
        InverseBondRestraint_exposer.def( "__str__", &__str__< ::SireMM::InverseBondRestraint > );
        InverseBondRestraint_exposer.def( "__repr__", &__str__< ::SireMM::InverseBondRestraint > );
    }

}
