// This file has been generated by Py++.

// (C) Christopher Woods, GPL >= 3 License

#include "boost/python.hpp"
#include "Helpers/clone_const_reference.hpp"
#include "InverseBondRestraints.pypp.hpp"

namespace bp = boost::python;

#include "SireError/errors.h"

#include "SireID/index.h"

#include "SireStream/datastream.h"

#include "SireStream/shareddatastream.h"

#include "SireUnits/units.h"

#include "inversebondrestraints.h"

#include <QDebug>

#include "inversebondrestraints.h"

SireMM::InverseBondRestraints __copy__(const SireMM::InverseBondRestraints &other){ return SireMM::InverseBondRestraints(other); }

#include "Helpers/copy.hpp"

#include "Qt/qdatastream.hpp"

#include "Helpers/str.hpp"

#include "Helpers/release_gil_policy.hpp"

#include "Helpers/len.hpp"

void register_InverseBondRestraints_class(){

    { //::SireMM::InverseBondRestraints
        typedef bp::class_< SireMM::InverseBondRestraints, bp::bases< SireMM::Restraints, SireBase::Property > > InverseBondRestraints_exposer_t;
        InverseBondRestraints_exposer_t InverseBondRestraints_exposer = InverseBondRestraints_exposer_t( "InverseBondRestraints", "This class provides the information for a collection of bond\nrestraints that can be added to a collection of molecues. Each\nrestraint can act on a pair of particles or a pair of the\ncentroids of two collections of particles.\nThe restaints are spherically symmetric, and\nare simple harmonic potentials\n", bp::init< >("Null constructor") );
        bp::scope InverseBondRestraints_scope( InverseBondRestraints_exposer );
        InverseBondRestraints_exposer.def( bp::init< QString const & >(( bp::arg("name") ), "") );
        InverseBondRestraints_exposer.def( bp::init< SireMM::InverseBondRestraint const & >(( bp::arg("restraint") ), "") );
        InverseBondRestraints_exposer.def( bp::init< QList< SireMM::InverseBondRestraint > const & >(( bp::arg("restraints") ), "") );
        InverseBondRestraints_exposer.def( bp::init< QString const &, SireMM::InverseBondRestraint const & >(( bp::arg("name"), bp::arg("restraint") ), "") );
        InverseBondRestraints_exposer.def( bp::init< QString const &, QList< SireMM::InverseBondRestraint > const & >(( bp::arg("name"), bp::arg("restraints") ), "") );
        InverseBondRestraints_exposer.def( bp::init< SireMM::InverseBondRestraints const & >(( bp::arg("other") ), "") );
        { //::SireMM::InverseBondRestraints::add
        
            typedef void ( ::SireMM::InverseBondRestraints::*add_function_type)( ::SireMM::InverseBondRestraint const & ) ;
            add_function_type add_function_value( &::SireMM::InverseBondRestraints::add );
            
            InverseBondRestraints_exposer.def( 
                "add"
                , add_function_value
                , ( bp::arg("restraint") )
                , bp::release_gil_policy()
                , "Add a restraint onto the list" );
        
        }
        { //::SireMM::InverseBondRestraints::add
        
            typedef void ( ::SireMM::InverseBondRestraints::*add_function_type)( ::SireMM::InverseBondRestraints const & ) ;
            add_function_type add_function_value( &::SireMM::InverseBondRestraints::add );
            
            InverseBondRestraints_exposer.def( 
                "add"
                , add_function_value
                , ( bp::arg("restraints") )
                , bp::release_gil_policy()
                , "Add a restraint onto the list" );
        
        }
        { //::SireMM::InverseBondRestraints::at
        
            typedef ::SireMM::InverseBondRestraint const & ( ::SireMM::InverseBondRestraints::*at_function_type)( int ) const;
            at_function_type at_function_value( &::SireMM::InverseBondRestraints::at );
            
            InverseBondRestraints_exposer.def( 
                "at"
                , at_function_value
                , ( bp::arg("i") )
                , bp::return_value_policy<bp::clone_const_reference, bp::release_gil_policy>()
                , "Return the ith restraint" );
        
        }
        { //::SireMM::InverseBondRestraints::atomRestraints
        
            typedef ::QList< SireMM::InverseBondRestraint > ( ::SireMM::InverseBondRestraints::*atomRestraints_function_type)(  ) const;
            atomRestraints_function_type atomRestraints_function_value( &::SireMM::InverseBondRestraints::atomRestraints );
            
            InverseBondRestraints_exposer.def( 
                "atomRestraints"
                , atomRestraints_function_value
                , bp::release_gil_policy()
                , "Return all of the atom restraints" );
        
        }
        { //::SireMM::InverseBondRestraints::centroidRestraints
        
            typedef ::QList< SireMM::InverseBondRestraint > ( ::SireMM::InverseBondRestraints::*centroidRestraints_function_type)(  ) const;
            centroidRestraints_function_type centroidRestraints_function_value( &::SireMM::InverseBondRestraints::centroidRestraints );
            
            InverseBondRestraints_exposer.def( 
                "centroidRestraints"
                , centroidRestraints_function_value
                , bp::release_gil_policy()
                , "Return all of the centroid restraints" );
        
        }
        { //::SireMM::InverseBondRestraints::count
        
            typedef int ( ::SireMM::InverseBondRestraints::*count_function_type)(  ) const;
            count_function_type count_function_value( &::SireMM::InverseBondRestraints::count );
            
            InverseBondRestraints_exposer.def( 
                "count"
                , count_function_value
                , bp::release_gil_policy()
                , "Return the number of restraints" );
        
        }
        { //::SireMM::InverseBondRestraints::getUsesPeriodicBoundaryConditions
        
            typedef bool ( ::SireMM::InverseBondRestraints::*getUsesPeriodicBoundaryConditions_function_type)(  ) const;
            getUsesPeriodicBoundaryConditions_function_type getUsesPeriodicBoundaryConditions_function_value( &::SireMM::InverseBondRestraints::getUsesPeriodicBoundaryConditions );
            
            InverseBondRestraints_exposer.def( 
                "getUsesPeriodicBoundaryConditions"
                , getUsesPeriodicBoundaryConditions_function_value
                , bp::release_gil_policy()
                , "Return whether or not periodic boundary conditions are to be used" );
        
        }
        { //::SireMM::InverseBondRestraints::hasAtomRestraints
        
            typedef bool ( ::SireMM::InverseBondRestraints::*hasAtomRestraints_function_type)(  ) const;
            hasAtomRestraints_function_type hasAtomRestraints_function_value( &::SireMM::InverseBondRestraints::hasAtomRestraints );
            
            InverseBondRestraints_exposer.def( 
                "hasAtomRestraints"
                , hasAtomRestraints_function_value
                , bp::release_gil_policy()
                , "Return whether or not there are any atom restraints" );
        
        }
        { //::SireMM::InverseBondRestraints::hasCentroidRestraints
        
            typedef bool ( ::SireMM::InverseBondRestraints::*hasCentroidRestraints_function_type)(  ) const;
            hasCentroidRestraints_function_type hasCentroidRestraints_function_value( &::SireMM::InverseBondRestraints::hasCentroidRestraints );
            
            InverseBondRestraints_exposer.def( 
                "hasCentroidRestraints"
                , hasCentroidRestraints_function_value
                , bp::release_gil_policy()
                , "Return whether or not there are any centroid restraints" );
        
        }
        { //::SireMM::InverseBondRestraints::isEmpty
        
            typedef bool ( ::SireMM::InverseBondRestraints::*isEmpty_function_type)(  ) const;
            isEmpty_function_type isEmpty_function_value( &::SireMM::InverseBondRestraints::isEmpty );
            
            InverseBondRestraints_exposer.def( 
                "isEmpty"
                , isEmpty_function_value
                , bp::release_gil_policy()
                , "Return whether or not this is empty" );
        
        }
        { //::SireMM::InverseBondRestraints::isNull
        
            typedef bool ( ::SireMM::InverseBondRestraints::*isNull_function_type)(  ) const;
            isNull_function_type isNull_function_value( &::SireMM::InverseBondRestraints::isNull );
            
            InverseBondRestraints_exposer.def( 
                "isNull"
                , isNull_function_value
                , bp::release_gil_policy()
                , "Return whether or not this is empty" );
        
        }
        { //::SireMM::InverseBondRestraints::nAtomRestraints
        
            typedef int ( ::SireMM::InverseBondRestraints::*nAtomRestraints_function_type)(  ) const;
            nAtomRestraints_function_type nAtomRestraints_function_value( &::SireMM::InverseBondRestraints::nAtomRestraints );
            
            InverseBondRestraints_exposer.def( 
                "nAtomRestraints"
                , nAtomRestraints_function_value
                , bp::release_gil_policy()
                , "Return the number of atom restraints" );
        
        }
        { //::SireMM::InverseBondRestraints::nCentroidRestraints
        
            typedef int ( ::SireMM::InverseBondRestraints::*nCentroidRestraints_function_type)(  ) const;
            nCentroidRestraints_function_type nCentroidRestraints_function_value( &::SireMM::InverseBondRestraints::nCentroidRestraints );
            
            InverseBondRestraints_exposer.def( 
                "nCentroidRestraints"
                , nCentroidRestraints_function_value
                , bp::release_gil_policy()
                , "Return the number of centroid restraints" );
        
        }
        { //::SireMM::InverseBondRestraints::nRestraints
        
            typedef int ( ::SireMM::InverseBondRestraints::*nRestraints_function_type)(  ) const;
            nRestraints_function_type nRestraints_function_value( &::SireMM::InverseBondRestraints::nRestraints );
            
            InverseBondRestraints_exposer.def( 
                "nRestraints"
                , nRestraints_function_value
                , bp::release_gil_policy()
                , "Return the number of restraints" );
        
        }
        InverseBondRestraints_exposer.def( bp::self != bp::self );
        InverseBondRestraints_exposer.def( bp::self + bp::other< SireMM::InverseBondRestraint >() );
        InverseBondRestraints_exposer.def( bp::self + bp::self );
        { //::SireMM::InverseBondRestraints::operator=
        
            typedef ::SireMM::InverseBondRestraints & ( ::SireMM::InverseBondRestraints::*assign_function_type)( ::SireMM::InverseBondRestraints const & ) ;
            assign_function_type assign_function_value( &::SireMM::InverseBondRestraints::operator= );
            
            InverseBondRestraints_exposer.def( 
                "assign"
                , assign_function_value
                , ( bp::arg("other") )
                , bp::return_self< >()
                , "" );
        
        }
        InverseBondRestraints_exposer.def( bp::self == bp::self );
        { //::SireMM::InverseBondRestraints::operator[]
        
            typedef ::SireMM::InverseBondRestraint const & ( ::SireMM::InverseBondRestraints::*__getitem___function_type)( int ) const;
            __getitem___function_type __getitem___function_value( &::SireMM::InverseBondRestraints::operator[] );
            
            InverseBondRestraints_exposer.def( 
                "__getitem__"
                , __getitem___function_value
                , ( bp::arg("i") )
                , bp::return_value_policy<bp::clone_const_reference, bp::release_gil_policy>()
                , "" );
        
        }
        { //::SireMM::InverseBondRestraints::restraints
        
            typedef ::QList< SireMM::InverseBondRestraint > ( ::SireMM::InverseBondRestraints::*restraints_function_type)(  ) const;
            restraints_function_type restraints_function_value( &::SireMM::InverseBondRestraints::restraints );
            
            InverseBondRestraints_exposer.def( 
                "restraints"
                , restraints_function_value
                , bp::release_gil_policy()
                , "Return all of the restraints" );
        
        }
        { //::SireMM::InverseBondRestraints::setUsesPeriodicBoundaryConditions
        
            typedef void ( ::SireMM::InverseBondRestraints::*setUsesPeriodicBoundaryConditions_function_type)( bool ) ;
            setUsesPeriodicBoundaryConditions_function_type setUsesPeriodicBoundaryConditions_function_value( &::SireMM::InverseBondRestraints::setUsesPeriodicBoundaryConditions );
            
            InverseBondRestraints_exposer.def( 
                "setUsesPeriodicBoundaryConditions"
                , setUsesPeriodicBoundaryConditions_function_value
                , ( bp::arg("use_pbc") )
                , bp::release_gil_policy()
                , "Set whether or not periodic boundary conditions are to be used" );
        
        }
        { //::SireMM::InverseBondRestraints::size
        
            typedef int ( ::SireMM::InverseBondRestraints::*size_function_type)(  ) const;
            size_function_type size_function_value( &::SireMM::InverseBondRestraints::size );
            
            InverseBondRestraints_exposer.def( 
                "size"
                , size_function_value
                , bp::release_gil_policy()
                , "Return the number of restraints" );
        
        }
        { //::SireMM::InverseBondRestraints::toString
        
            typedef ::QString ( ::SireMM::InverseBondRestraints::*toString_function_type)(  ) const;
            toString_function_type toString_function_value( &::SireMM::InverseBondRestraints::toString );
            
            InverseBondRestraints_exposer.def( 
                "toString"
                , toString_function_value
                , bp::release_gil_policy()
                , "" );
        
        }
        { //::SireMM::InverseBondRestraints::typeName
        
            typedef char const * ( *typeName_function_type )(  );
            typeName_function_type typeName_function_value( &::SireMM::InverseBondRestraints::typeName );
            
            InverseBondRestraints_exposer.def( 
                "typeName"
                , typeName_function_value
                , bp::release_gil_policy()
                , "" );
        
        }
        { //::SireMM::InverseBondRestraints::what
        
            typedef char const * ( ::SireMM::InverseBondRestraints::*what_function_type)(  ) const;
            what_function_type what_function_value( &::SireMM::InverseBondRestraints::what );
            
            InverseBondRestraints_exposer.def( 
                "what"
                , what_function_value
                , bp::release_gil_policy()
                , "" );
        
        }
        InverseBondRestraints_exposer.staticmethod( "typeName" );
        InverseBondRestraints_exposer.def( "__copy__", &__copy__<SireMM::InverseBondRestraints>);
        InverseBondRestraints_exposer.def( "__deepcopy__", &__copy__<SireMM::InverseBondRestraints>);
        InverseBondRestraints_exposer.def( "clone", &__copy__<SireMM::InverseBondRestraints>);
        InverseBondRestraints_exposer.def( "__rlshift__", &__rlshift__QDataStream< ::SireMM::InverseBondRestraints >,
                            bp::return_internal_reference<1, bp::with_custodian_and_ward<1,2> >() );
        InverseBondRestraints_exposer.def( "__rrshift__", &__rrshift__QDataStream< ::SireMM::InverseBondRestraints >,
                            bp::return_internal_reference<1, bp::with_custodian_and_ward<1,2> >() );
        InverseBondRestraints_exposer.def_pickle(sire_pickle_suite< ::SireMM::InverseBondRestraints >());
        InverseBondRestraints_exposer.def( "__str__", &__str__< ::SireMM::InverseBondRestraints > );
        InverseBondRestraints_exposer.def( "__repr__", &__str__< ::SireMM::InverseBondRestraints > );
        InverseBondRestraints_exposer.def( "__len__", &__len_size< ::SireMM::InverseBondRestraints > );
    }

}
