// This file has been generated by Py++.

// (C) Christopher Woods, GPL >= 3 License

#ifndef LJException_hpp__pyplusplus_wrapper
#define LJException_hpp__pyplusplus_wrapper

void register_LJException_class();

#endif//LJException_hpp__pyplusplus_wrapper
