// This file has been generated by Py++.

// (C) Christopher Woods, GPL >= 3 License

#ifndef LJParameterName_hpp__pyplusplus_wrapper
#define LJParameterName_hpp__pyplusplus_wrapper

void register_LJParameterName_class();

#endif//LJParameterName_hpp__pyplusplus_wrapper
