// This file has been generated by Py++.

// (C) Christopher Woods, GPL >= 3 License

#ifndef MorsePotentialRestraints_hpp__pyplusplus_wrapper
#define MorsePotentialRestraints_hpp__pyplusplus_wrapper

void register_MorsePotentialRestraints_class();

#endif//MorsePotentialRestraints_hpp__pyplusplus_wrapper
