// This file has been generated by Py++.

// (C) Christopher Woods, GPL >= 3 License

#ifndef MorsePotentialRestraint_hpp__pyplusplus_wrapper
#define MorsePotentialRestraint_hpp__pyplusplus_wrapper

void register_MorsePotentialRestraint_class();

#endif//MorsePotentialRestraint_hpp__pyplusplus_wrapper
