// This file has been generated by Py++.

// (C) Christopher Woods, GPL >= 3 License

#ifndef Mover_Bond__hpp__pyplusplus_wrapper
#define Mover_Bond__hpp__pyplusplus_wrapper

void register_Mover_Bond__class();

#endif//Mover_Bond__hpp__pyplusplus_wrapper
