// This file has been generated by Py++.

// (C) Christopher Woods, GPL >= 3 License

#ifndef PositionalRestraints_hpp__pyplusplus_wrapper
#define PositionalRestraints_hpp__pyplusplus_wrapper

void register_PositionalRestraints_class();

#endif//PositionalRestraints_hpp__pyplusplus_wrapper
