// This file has been generated by Py++.

// (C) Christopher Woods, GPL >= 3 License

#ifndef RestraintComponent_hpp__pyplusplus_wrapper
#define RestraintComponent_hpp__pyplusplus_wrapper

void register_RestraintComponent_class();

#endif//RestraintComponent_hpp__pyplusplus_wrapper
