// This file has been generated by Py++.

// (C) Christopher Woods, GPL >= 3 License

#ifndef RestraintFF_hpp__pyplusplus_wrapper
#define RestraintFF_hpp__pyplusplus_wrapper

void register_RestraintFF_class();

#endif//RestraintFF_hpp__pyplusplus_wrapper
