// This file has been generated by Py++.

// (C) Christopher Woods, GPL >= 3 License

#ifndef Restraints_hpp__pyplusplus_wrapper
#define Restraints_hpp__pyplusplus_wrapper

void register_Restraints_class();

#endif//Restraints_hpp__pyplusplus_wrapper
