// This file has been generated by Py++.

// (C) Christopher Woods, GPL >= 3 License

#ifndef RMSDRestraint_hpp__pyplusplus_wrapper
#define RMSDRestraint_hpp__pyplusplus_wrapper

void register_RMSDRestraint_class();

#endif//RMSDRestraint_hpp__pyplusplus_wrapper
