// This file has been generated by Py++.

// (C) Christopher Woods, GPL >= 3 License

#ifndef SelectorMAngle_hpp__pyplusplus_wrapper
#define SelectorMAngle_hpp__pyplusplus_wrapper

void register_SelectorMAngle_class();

#endif//SelectorMAngle_hpp__pyplusplus_wrapper
