// This file has been generated by Py++.

// (C) Christopher Woods, GPL >= 3 License

#ifndef TwoAtomFunctions_hpp__pyplusplus_wrapper
#define TwoAtomFunctions_hpp__pyplusplus_wrapper

void register_TwoAtomFunctions_class();

#endif//TwoAtomFunctions_hpp__pyplusplus_wrapper
