// This file has been generated by Py++.

// (C) Christopher Woods, GPL >= 3 License

#ifndef Flexibility_hpp__pyplusplus_wrapper
#define Flexibility_hpp__pyplusplus_wrapper

void register_Flexibility_class();

#endif//Flexibility_hpp__pyplusplus_wrapper
