// This file has been generated by Py++.

// (C) Christopher Woods, GPL >= 3 License

#ifndef GetCOGPoint_hpp__pyplusplus_wrapper
#define GetCOGPoint_hpp__pyplusplus_wrapper

void register_GetCOGPoint_class();

#endif//GetCOGPoint_hpp__pyplusplus_wrapper
