// This file has been generated by Py++.

// (C) Christopher Woods, GPL >= 3 License

#ifndef GetCOMPoint_hpp__pyplusplus_wrapper
#define GetCOMPoint_hpp__pyplusplus_wrapper

void register_GetCOMPoint_class();

#endif//GetCOMPoint_hpp__pyplusplus_wrapper
