// This file has been generated by Py++.

// (C) Christopher Woods, GPL >= 3 License

#ifndef MaxwellBoltzmann_hpp__pyplusplus_wrapper
#define MaxwellBoltzmann_hpp__pyplusplus_wrapper

void register_MaxwellBoltzmann_class();

#endif//MaxwellBoltzmann_hpp__pyplusplus_wrapper
