// This file has been generated by Py++.

// (C) Christopher Woods, GPL >= 3 License

#ifndef MolecularDynamics_hpp__pyplusplus_wrapper
#define MolecularDynamics_hpp__pyplusplus_wrapper

void register_MolecularDynamics_class();

#endif//MolecularDynamics_hpp__pyplusplus_wrapper
