// This file has been generated by Py++.

// (C) Christopher Woods, GPL >= 3 License

#ifndef MolInserter_hpp__pyplusplus_wrapper
#define MolInserter_hpp__pyplusplus_wrapper

void register_MolInserter_class();

#endif//MolInserter_hpp__pyplusplus_wrapper
