// This file has been generated by Py++.

// (C) Christopher Woods, GPL >= 3 License

#ifndef NullSupraSubMove_hpp__pyplusplus_wrapper
#define NullSupraSubMove_hpp__pyplusplus_wrapper

void register_NullSupraSubMove_class();

#endif//NullSupraSubMove_hpp__pyplusplus_wrapper
