// This file has been generated by Py++.

// (C) Christopher Woods, GPL >= 3 License

#ifndef OpenMMFrEnergyST_hpp__pyplusplus_wrapper
#define OpenMMFrEnergyST_hpp__pyplusplus_wrapper

void register_OpenMMFrEnergyST_class();

#endif//OpenMMFrEnergyST_hpp__pyplusplus_wrapper
