// This file has been generated by Py++.

// (C) Christopher Woods, GPL >= 3 License

#ifndef RepExMove2_hpp__pyplusplus_wrapper
#define RepExMove2_hpp__pyplusplus_wrapper

void register_RepExMove2_class();

#endif//RepExMove2_hpp__pyplusplus_wrapper
