// This file has been generated by Py++.

// (C) Christopher Woods, GPL >= 3 License

#ifndef Replicas_hpp__pyplusplus_wrapper
#define Replicas_hpp__pyplusplus_wrapper

void register_Replicas_class();

#endif//Replicas_hpp__pyplusplus_wrapper
