// This file has been generated by Py++.

// (C) Christopher Woods, GPL >= 3 License

#ifndef ArcCos_hpp__pyplusplus_wrapper
#define ArcCos_hpp__pyplusplus_wrapper

void register_ArcCos_class();

#endif//ArcCos_hpp__pyplusplus_wrapper
