// This file has been generated by Py++.

// (C) Christopher Woods, GPL >= 3 License

#ifndef ArcSinh_hpp__pyplusplus_wrapper
#define ArcSinh_hpp__pyplusplus_wrapper

void register_ArcSinh_class();

#endif//ArcSinh_hpp__pyplusplus_wrapper
