// This file has been generated by Py++.

// (C) Christopher Woods, GPL >= 3 License

#ifndef DoubleFunc_hpp__pyplusplus_wrapper
#define DoubleFunc_hpp__pyplusplus_wrapper

void register_DoubleFunc_class();

#endif//DoubleFunc_hpp__pyplusplus_wrapper
