// This file has been generated by Py++.

// (C) Christopher Woods, GPL >= 3 License

#ifndef IntegrationConstant_hpp__pyplusplus_wrapper
#define IntegrationConstant_hpp__pyplusplus_wrapper

void register_IntegrationConstant_class();

#endif//IntegrationConstant_hpp__pyplusplus_wrapper
