// This file has been generated by Py++.

// (C) Christopher Woods, GPL >= 3 License

#ifndef LambdaSchedule_hpp__pyplusplus_wrapper
#define LambdaSchedule_hpp__pyplusplus_wrapper

void register_LambdaSchedule_class();

#endif//LambdaSchedule_hpp__pyplusplus_wrapper
