// This file has been generated by Py++.

// (C) Christopher Woods, GPL >= 3 License

#ifndef LessThan_hpp__pyplusplus_wrapper
#define LessThan_hpp__pyplusplus_wrapper

void register_LessThan_class();

#endif//LessThan_hpp__pyplusplus_wrapper
