// This file has been generated by Py++.

// (C) Christopher Woods, GPL >= 3 License

#ifndef SingleFunc_hpp__pyplusplus_wrapper
#define SingleFunc_hpp__pyplusplus_wrapper

void register_SingleFunc_class();

#endif//SingleFunc_hpp__pyplusplus_wrapper
