// This file has been generated by Py++.

// (C) Christopher Woods, GPL >= 3 License

#ifndef DistVector_hpp__pyplusplus_wrapper
#define DistVector_hpp__pyplusplus_wrapper

void register_DistVector_class();

#endif//DistVector_hpp__pyplusplus_wrapper
