// This file has been generated by Py++.

// (C) Christopher Woods, GPL >= 3 License

#ifndef EnergyTrajectory_hpp__pyplusplus_wrapper
#define EnergyTrajectory_hpp__pyplusplus_wrapper

void register_EnergyTrajectory_class();

#endif//EnergyTrajectory_hpp__pyplusplus_wrapper
