// This file has been generated by Py++.

// (C) Christopher Woods, GPL >= 3 License

#ifndef Histogram_hpp__pyplusplus_wrapper
#define Histogram_hpp__pyplusplus_wrapper

void register_Histogram_class();

#endif//Histogram_hpp__pyplusplus_wrapper
