// This file has been generated by Py++.

// (C) Christopher Woods, GPL >= 3 License

#ifndef Line_hpp__pyplusplus_wrapper
#define Line_hpp__pyplusplus_wrapper

void register_Line_class();

#endif//Line_hpp__pyplusplus_wrapper
