// This file has been generated by Py++.

// (C) Christopher Woods, GPL >= 3 License

#ifndef Median_hpp__pyplusplus_wrapper
#define Median_hpp__pyplusplus_wrapper

void register_Median_class();

#endif//Median_hpp__pyplusplus_wrapper
