// This file has been generated by Py++.

// (C) Christopher Woods, GPL >= 3 License

#ifndef MultiUInt_hpp__pyplusplus_wrapper
#define MultiUInt_hpp__pyplusplus_wrapper

void register_MultiUInt_class();

#endif//MultiUInt_hpp__pyplusplus_wrapper
