// This file has been generated by Py++.

// (C) Christopher Woods, GPL >= 3 License

#ifndef Plane_hpp__pyplusplus_wrapper
#define Plane_hpp__pyplusplus_wrapper

void register_Plane_class();

#endif//Plane_hpp__pyplusplus_wrapper
