// This file has been generated by Py++.

// (C) Christopher Woods, GPL >= 3 License

#ifndef Rational_hpp__pyplusplus_wrapper
#define Rational_hpp__pyplusplus_wrapper

void register_Rational_class();

#endif//Rational_hpp__pyplusplus_wrapper
