// This file has been generated by Py++.

// (C) Christopher Woods, GPL >= 3 License

#ifndef SphereProperty_hpp__pyplusplus_wrapper
#define SphereProperty_hpp__pyplusplus_wrapper

void register_SphereProperty_class();

#endif//SphereProperty_hpp__pyplusplus_wrapper
