// This file has been generated by Py++.

// (C) Christopher Woods, GPL >= 3 License

#ifndef TrigArray2D_Matrix__hpp__pyplusplus_wrapper
#define TrigArray2D_Matrix__hpp__pyplusplus_wrapper

void register_TrigArray2D_Matrix__class();

#endif//TrigArray2D_Matrix__hpp__pyplusplus_wrapper
