// This file has been generated by Py++.

// (C) Christopher Woods, GPL >= 3 License

#ifndef VectorArrayProperty_hpp__pyplusplus_wrapper
#define VectorArrayProperty_hpp__pyplusplus_wrapper

void register_VectorArrayProperty_class();

#endif//VectorArrayProperty_hpp__pyplusplus_wrapper
