// This file has been generated by Py++.

// (C) Christopher Woods, GPL >= 3 License

#ifndef GroAtom_hpp__pyplusplus_wrapper
#define GroAtom_hpp__pyplusplus_wrapper

void register_GroAtom_class();

#endif//GroAtom_hpp__pyplusplus_wrapper
