// This file has been generated by Py++.

// (C) Christopher Woods, GPL >= 3 License

#ifndef Mol2_hpp__pyplusplus_wrapper
#define Mol2_hpp__pyplusplus_wrapper

void register_Mol2_class();

#endif//Mol2_hpp__pyplusplus_wrapper
