// This file has been generated by Py++.

// (C) Christopher Woods, GPL >= 3 License

#ifndef PDBx_hpp__pyplusplus_wrapper
#define PDBx_hpp__pyplusplus_wrapper

void register_PDBx_class();

#endif//PDBx_hpp__pyplusplus_wrapper
