// This file has been generated by Py++.

// (C) Christopher Woods, GPL >= 3 License

#ifndef OpenMMFrEnergyDT_hpp__pyplusplus_wrapper
#define OpenMMFrEnergyDT_hpp__pyplusplus_wrapper

void register_OpenMMFrEnergyDT_class();

#endif//OpenMMFrEnergyDT_hpp__pyplusplus_wrapper
